/**
 * @packageDocumentation
 * @module api.functional.employee
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { CreateEmployee, Employee } from '../../dto/employee/employee.dto';

export * as all from './all';
export * as list from './list';

/**
 * @controller EmployeeController.getOne
 * @path GET /employee/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getOne(
  connection: IConnection,
  id: string,
): Promise<getOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...getOne.METADATA,
    path: getOne.path(id),
  } as const);
}
export namespace getOne {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/employee/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/employee/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller EmployeeController.create
 * @path POST /employee
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createEmployee: create.Input,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...create.METADATA,
      path: create.path(),
    } as const,
    createEmployee,
  );
}
export namespace create {
  export type Input = Primitive<CreateEmployee>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/employee',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/employee';
  };
}

/**
 * @controller EmployeeController.updateEmployee
 * @path PUT /employee/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateEmployee(
  connection: IConnection,
  id: string,
  update: updateEmployee.Input,
): Promise<updateEmployee.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...updateEmployee.METADATA,
      path: updateEmployee.path(id),
    } as const,
    update,
  );
}
export namespace updateEmployee {
  export type Input = Primitive<Employee>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'PUT',
    path: '/employee/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/employee/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller EmployeeController.deleteEmployee
 * @path DELETE /employee/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteEmployee(
  connection: IConnection,
  id: string,
): Promise<deleteEmployee.Output> {
  return PlainFetcher.fetch(connection, {
    ...deleteEmployee.METADATA,
    path: deleteEmployee.path(id),
  } as const);
}
export namespace deleteEmployee {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'DELETE',
    path: '/employee/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/employee/${encodeURIComponent(id ?? 'null')}`;
  };
}
