/**
 * @packageDocumentation
 * @module api.functional.student_state.active
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

/**
 * @controller StudentStateController.findAllActive
 * @path GET /student-state/active
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAllActive(
  connection: IConnection,
): Promise<findAllActive.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAllActive.METADATA,
    path: findAllActive.path(),
  } as const);
}
export namespace findAllActive {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/student-state/active',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/student-state/active';
  };
}
