/**
 * @packageDocumentation
 * @module api.functional.financial_management
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type {
  CreateFinancialManagement,
  UpdateFinancialManagement,
} from '../../dto/financial-management/financial-management.dto';

export * as query from './query';
export * as advanced_query from './advanced_query';

/**
 * @controller FinancialManagementController.create
 * @path POST /financial-management
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createFinancialManagementDto: create.Input,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...create.METADATA,
      path: create.path(),
    } as const,
    createFinancialManagementDto,
  );
}
export namespace create {
  export type Input = Primitive<CreateFinancialManagement>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/financial-management',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/financial-management';
  };
}

/**
 * @controller FinancialManagementController.findAll
 * @path GET /financial-management
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    path: findAll.path(),
  } as const);
}
export namespace findAll {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/financial-management',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/financial-management';
  };
}

/**
 * @controller FinancialManagementController.findOne
 * @path GET /financial-management/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    path: findOne.path(id),
  } as const);
}
export namespace findOne {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/financial-management/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/financial-management/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller FinancialManagementController.update
 * @path PATCH /financial-management/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateFinancialManagementDto: update.Input,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...update.METADATA,
      path: update.path(id),
    } as const,
    updateFinancialManagementDto,
  );
}
export namespace update {
  export type Input = Primitive<UpdateFinancialManagement>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'PATCH',
    path: '/financial-management/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/financial-management/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller FinancialManagementController.remove
 * @path DELETE /financial-management/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    path: remove.path(id),
  } as const);
}
export namespace remove {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'DELETE',
    path: '/financial-management/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/financial-management/${encodeURIComponent(id ?? 'null')}`;
  };
}
