/**
 * @packageDocumentation
 * @module api.functional.dashboard.teacher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { QueryDashboard } from '../../../dto/dashboard/query.dto';

/**
 * @controller DashboardController.getNewTeacher
 * @path GET /dashboard/teacher
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getNewTeacher(
  connection: IConnection,
  query: getNewTeacher.Query,
): Promise<getNewTeacher.Output> {
  return PlainFetcher.fetch(connection, {
    ...getNewTeacher.METADATA,
    path: getNewTeacher.path(query),
  } as const);
}
export namespace getNewTeacher {
  export type Query = Resolved<QueryDashboard>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/dashboard/teacher',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (query: getNewTeacher.Query): string => {
    const variables: Record<any, any> = query as any;
    const search: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(variables))
      if (value === undefined) continue;
      else if (Array.isArray(value))
        value.forEach((elem) => search.append(key, String(elem)));
      else search.set(key, String(value));
    const encoded: string = search.toString();
    return `/dashboard/teacher${encoded.length ? `?${encoded}` : ''}`;
  };
}
