/**
 * @packageDocumentation
 * @module api.functional.dashboard.$class
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { QueryDashboard } from '../../../dto/dashboard/query.dto';

/**
 * @controller DashboardController.getNewClass
 * @path GET /dashboard/class
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getNewClass(
  connection: IConnection,
  query: getNewClass.Query,
): Promise<getNewClass.Output> {
  return PlainFetcher.fetch(connection, {
    ...getNewClass.METADATA,
    path: getNewClass.path(query),
  } as const);
}
export namespace getNewClass {
  export type Query = Resolved<QueryDashboard>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/dashboard/class',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (query: getNewClass.Query): string => {
    const variables: Record<any, any> = query as any;
    const search: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(variables))
      if (value === undefined) continue;
      else if (Array.isArray(value))
        value.forEach((elem) => search.append(key, String(elem)));
      else search.set(key, String(value));
    const encoded: string = search.toString();
    return `/dashboard/class${encoded.length ? `?${encoded}` : ''}`;
  };
}
