/**
 * @packageDocumentation
 * @module api.functional.$class
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { Class, CreateClass } from '../../dto/class/class.dto';

export * as all from './all';
export * as list from './list';
export * as search from './search';

/**
 * @controller ClassController.getClass
 * @path GET /class/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getClass(
  connection: IConnection,
  id: string,
): Promise<getClass.Output> {
  return PlainFetcher.fetch(connection, {
    ...getClass.METADATA,
    path: getClass.path(id),
  } as const);
}
export namespace getClass {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/class/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/class/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller ClassController.create
 * @path POST /class
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createClass: create.Input,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...create.METADATA,
      path: create.path(),
    } as const,
    createClass,
  );
}
export namespace create {
  export type Input = Primitive<CreateClass>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/class',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/class';
  };
}

/**
 * @controller ClassController.updateClass
 * @path PUT /class/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function updateClass(
  connection: IConnection,
  id: string,
  update: updateClass.Input,
): Promise<updateClass.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...updateClass.METADATA,
      path: updateClass.path(id),
    } as const,
    update,
  );
}
export namespace updateClass {
  export type Input = Primitive<Class>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'PUT',
    path: '/class/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/class/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller ClassController.deleteClass
 * @path DELETE /class/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function deleteClass(
  connection: IConnection,
  id: string,
): Promise<deleteClass.Output> {
  return PlainFetcher.fetch(connection, {
    ...deleteClass.METADATA,
    path: deleteClass.path(id),
  } as const);
}
export namespace deleteClass {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'DELETE',
    path: '/class/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/class/${encodeURIComponent(id ?? 'null')}`;
  };
}
