/**
 * @packageDocumentation
 * @module api.functional.schedule.addFromSchedule
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { AddStudentFromSchedule } from '../../../dto/schedule/add-student.dto';

/**
 * @controller ScheduleController.addStudentFromSchedule
 * @path POST /schedule/addFromSchedule
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function addStudentFromSchedule(
  connection: IConnection,
  addStudent: addStudentFromSchedule.Input,
): Promise<addStudentFromSchedule.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...addStudentFromSchedule.METADATA,
      path: addStudentFromSchedule.path(),
    } as const,
    addStudent,
  );
}
export namespace addStudentFromSchedule {
  export type Input = Primitive<AddStudentFromSchedule>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/schedule/addFromSchedule',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/schedule/addFromSchedule';
  };
}
