/**
 * @packageDocumentation
 * @module api.functional.$class.search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { QueryClass } from '../../../dto/class/query-class.dto';

/**
 * @controller ClassController.queryClassForTeacher
 * @path GET /class/search
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function queryClassForTeacher(
  connection: IConnection,
  queryClass: queryClassForTeacher.Query,
): Promise<queryClassForTeacher.Output> {
  return PlainFetcher.fetch(connection, {
    ...queryClassForTeacher.METADATA,
    path: queryClassForTeacher.path(queryClass),
  } as const);
}
export namespace queryClassForTeacher {
  export type Query = Resolved<QueryClass>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/class/search',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (queryClass: queryClassForTeacher.Query): string => {
    const variables: Record<any, any> = queryClass as any;
    const search: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(variables))
      if (value === undefined) continue;
      else if (Array.isArray(value))
        value.forEach((elem) => search.append(key, String(elem)));
      else search.set(key, String(value));
    const encoded: string = search.toString();
    return `/class/search${encoded.length ? `?${encoded}` : ''}`;
  };
}
