/**
 * @packageDocumentation
 * @module api.functional.dashboard.course
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { queryTopCourse } from '../../../dto/dashboard/query-topCourse.dto';

/**
 * @controller DashboardController.getCourse
 * @path GET /dashboard/course
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getCourse(
  connection: IConnection,
  query: getCourse.Query,
): Promise<getCourse.Output> {
  return PlainFetcher.fetch(connection, {
    ...getCourse.METADATA,
    path: getCourse.path(query),
  } as const);
}
export namespace getCourse {
  export type Query = Resolved<queryTopCourse>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/dashboard/course',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (query: getCourse.Query): string => {
    const variables: Record<any, any> = query as any;
    const search: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(variables))
      if (value === undefined) continue;
      else if (Array.isArray(value))
        value.forEach((elem) => search.append(key, String(elem)));
      else search.set(key, String(value));
    const encoded: string = search.toString();
    return `/dashboard/course${encoded.length ? `?${encoded}` : ''}`;
  };
}
