/**
 * @packageDocumentation
 * @module api.functional.vat_management
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type {
  CreateVATManagement,
  UpdateVATManagement,
} from '../../dto/vat-management/vat-management.dto';

export * as query from './query';
export * as advanced_query from './advanced_query';

/**
 * @controller VatManagementController.create
 * @path POST /vat-management
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createVatManagementDto: create.Input,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...create.METADATA,
      path: create.path(),
    } as const,
    createVatManagementDto,
  );
}
export namespace create {
  export type Input = Primitive<CreateVATManagement>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/vat-management',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/vat-management';
  };
}

/**
 * @controller VatManagementController.findAll
 * @path GET /vat-management
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    path: findAll.path(),
  } as const);
}
export namespace findAll {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/vat-management',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/vat-management';
  };
}

/**
 * @controller VatManagementController.findOne
 * @path GET /vat-management/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    path: findOne.path(id),
  } as const);
}
export namespace findOne {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/vat-management/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/vat-management/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller VatManagementController.update
 * @path PATCH /vat-management/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateVatManagementDto: update.Input,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...update.METADATA,
      path: update.path(id),
    } as const,
    updateVatManagementDto,
  );
}
export namespace update {
  export type Input = Primitive<UpdateVATManagement>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'PATCH',
    path: '/vat-management/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/vat-management/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller VatManagementController.remove
 * @path DELETE /vat-management/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    path: remove.path(id),
  } as const);
}
export namespace remove {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'DELETE',
    path: '/vat-management/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/vat-management/${encodeURIComponent(id ?? 'null')}`;
  };
}
