/**
 * @packageDocumentation
 * @module api.functional.users.all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

/**
 * @controller UsersController.getAllUser
 * @path GET /users/all
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getAllUser(
  connection: IConnection,
): Promise<getAllUser.Output> {
  return PlainFetcher.fetch(connection, {
    ...getAllUser.METADATA,
    path: getAllUser.path(),
  } as const);
}
export namespace getAllUser {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/users/all',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/users/all';
  };
}
