/**
 * @packageDocumentation
 * @module api.functional.comment.query
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as student from './student';
export * as teacher from './teacher';
