/**
 * @packageDocumentation
 * @module api.functional.dayoff
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { CreateDayoff, UpdateDayoff } from '../../dto/dayoff/dayoff.dto';

export * as query from './query';

/**
 * @controller DayoffController.create
 * @path POST /dayoff
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createDayoff: create.Input,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...create.METADATA,
      path: create.path(),
    } as const,
    createDayoff,
  );
}
export namespace create {
  export type Input = Primitive<CreateDayoff>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/dayoff',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/dayoff';
  };
}

/**
 * @controller DayoffController.findAll
 * @path GET /dayoff
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    path: findAll.path(),
  } as const);
}
export namespace findAll {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/dayoff',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/dayoff';
  };
}

/**
 * @controller DayoffController.findOne
 * @path GET /dayoff/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    path: findOne.path(id),
  } as const);
}
export namespace findOne {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/dayoff/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/dayoff/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller DayoffController.update
 * @path PATCH /dayoff/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateDayoff: update.Input,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...update.METADATA,
      path: update.path(id),
    } as const,
    updateDayoff,
  );
}
export namespace update {
  export type Input = Primitive<UpdateDayoff>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'PATCH',
    path: '/dayoff/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/dayoff/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller DayoffController.remove
 * @path DELETE /dayoff/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    path: remove.path(id),
  } as const);
}
export namespace remove {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'DELETE',
    path: '/dayoff/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/dayoff/${encodeURIComponent(id ?? 'null')}`;
  };
}
