/**
 * @packageDocumentation
 * @module api.functional.dashboard
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
export * as student from './student';
export * as teacher from './teacher';
export * as $class from './$class';
export * as revenue from './revenue';
export * as course from './course';
