/**
 * @packageDocumentation
 * @module api.functional.schedule.createDefaultSchedule
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { CreateSchedule } from '../../../dto/schedule/create-schedule.dto';

/**
 * @controller ScheduleController.makenew
 * @path POST /schedule/createDefaultSchedule
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function makenew(
  connection: IConnection,
  defaultSchedule: makenew.Input,
): Promise<makenew.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...makenew.METADATA,
      path: makenew.path(),
    } as const,
    defaultSchedule,
  );
}
export namespace makenew {
  export type Input = Primitive<CreateSchedule>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/schedule/createDefaultSchedule',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/schedule/createDefaultSchedule';
  };
}
