/**
 * @packageDocumentation
 * @module api.functional.setting.office
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type {
  CreateOffice,
  UpdateOffice,
} from '../../../dto/office/office.dto';

export * as query from './query';

/**
 * @controller OfficeController.create
 * @path POST /setting/office
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function create(
  connection: IConnection,
  createSettingDto: create.Input,
): Promise<create.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...create.METADATA,
      path: create.path(),
    } as const,
    createSettingDto,
  );
}
export namespace create {
  export type Input = Primitive<CreateOffice>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'POST',
    path: '/setting/office',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/setting/office';
  };
}

/**
 * @controller OfficeController.findAll
 * @path GET /setting/office
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findAll(
  connection: IConnection,
): Promise<findAll.Output> {
  return PlainFetcher.fetch(connection, {
    ...findAll.METADATA,
    path: findAll.path(),
  } as const);
}
export namespace findAll {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/setting/office',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (): string => {
    return '/setting/office';
  };
}

/**
 * @controller OfficeController.findOne
 * @path GET /setting/office/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function findOne(
  connection: IConnection,
  id: string,
): Promise<findOne.Output> {
  return PlainFetcher.fetch(connection, {
    ...findOne.METADATA,
    path: findOne.path(id),
  } as const);
}
export namespace findOne {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/setting/office/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/setting/office/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller OfficeController.update
 * @path PATCH /setting/office/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function update(
  connection: IConnection,
  id: string,
  updateOffice: update.Input,
): Promise<update.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...(connection.headers ?? {}),
        'Content-Type': 'application/json',
      },
    },
    {
      ...update.METADATA,
      path: update.path(id),
    } as const,
    updateOffice,
  );
}
export namespace update {
  export type Input = Primitive<UpdateOffice>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'PATCH',
    path: '/setting/office/:id',
    request: {
      type: 'application/json',
      encrypted: false,
    },
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/setting/office/${encodeURIComponent(id ?? 'null')}`;
  };
}

/**
 * @controller OfficeController.remove
 * @path DELETE /setting/office/:id
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function remove(
  connection: IConnection,
  id: string,
): Promise<remove.Output> {
  return PlainFetcher.fetch(connection, {
    ...remove.METADATA,
    path: remove.path(id),
  } as const);
}
export namespace remove {
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'DELETE',
    path: '/setting/office/:id',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (id: string): string => {
    return `/setting/office/${encodeURIComponent(id ?? 'null')}`;
  };
}
