/**
 * @packageDocumentation
 * @module api.functional.schedule.by_class
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
//================================================================
import type { IConnection, Primitive, Resolved } from '@nestia/fetcher';
import { PlainFetcher } from '@nestia/fetcher/lib/PlainFetcher';

import type { ClassQuerySchedule } from '../../../dto/schedule/class-query.dto';

/**
 * @controller ScheduleController.getScheduleByClassId
 * @path GET /schedule/by-class
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function getScheduleByClassId(
  connection: IConnection,
  query: getScheduleByClassId.Query,
): Promise<getScheduleByClassId.Output> {
  return PlainFetcher.fetch(connection, {
    ...getScheduleByClassId.METADATA,
    path: getScheduleByClassId.path(query),
  } as const);
}
export namespace getScheduleByClassId {
  export type Query = Resolved<ClassQuerySchedule>;
  export type Output = Primitive<any>;

  export const METADATA = {
    method: 'GET',
    path: '/schedule/by-class',
    request: null,
    response: {
      type: 'application/json',
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = (query: getScheduleByClassId.Query): string => {
    const variables: Record<any, any> = query as any;
    const search: URLSearchParams = new URLSearchParams();
    for (const [key, value] of Object.entries(variables))
      if (value === undefined) continue;
      else if (Array.isArray(value))
        value.forEach((elem) => search.append(key, String(elem)));
      else search.set(key, String(value));
    const encoded: string = search.toString();
    return `/schedule/by-class${encoded.length ? `?${encoded}` : ''}`;
  };
}
